Calculator homework
marmatu/sft2021MarijusM pull request #2
Opened 2021-08-10 13:24 UTC by marmatu

Calculator tests for test automation homework

2021-08-11 12:11 UTC, mdovile requested changes
Puikiai! Tvarkingai viskas, logiškai, geri testai.  
Dar būtų galima parašyt papildomų testų, pvz dalyba iš 0 (turi atsirasti erroras "Divide by zero error!") arba įvesti ne skaičių į input fieldą ("Number 1 is not a number"). Dar Integers only funkcijos veikimą patikrinti. Bet čia jeigu norisi tobulėti ir yra laisvo laiko 😀 Nes šiaip gerai viskas

2021-08-12 12:56 UTC, marmatu commented on tests/calculator-homework.spec.js
> +const inputOne = '6';
Gera idėja - pritaikysiu. Tik čia turbūt reiktų generuoti skaičius neįtraukiant 0 (kadangi divide testas su 0 failins net ir operacijai veikiant teisingai)?

2021-08-12 12:56 UTC, marmatu commented on tests/calculator-homework.spec.js
> +      const reqElementsVisible = await calculatorPage.reqElementsVisible();
Dėl šito ir pats abejojau, pabandysiu perkelti į atskirą testą. Vienintelė bėda, kad be šito asserto testuojant buildus be reikiamų laukų testai sustoja ir užtrunką kiek laiko, kol jie failina (matyt todėl, kad testai bando užpildyti nesančius laukus). Ar tai yra normalu, ar reiktų bandyti apeiti tuos testus kitais būdais?

2021-08-12 12:56 UTC, marmatu commented on pages/calculatorPage.js
> +    return allElements.every(Boolean);
Pabandysiu pritaikyti.

2021-08-12 14:22 UTC, mdovile commented on tests/calculator-homework.spec.js
> +      const reqElementsVisible = await calculatorPage.reqElementsVisible();
Gal eina kur nors nustatyti konfigūracijoje kokį mažesnį timeout pvz 5 sekundės - jeigu neranda reikiamo elemento ant kurio clickinti, tiesiog nufailintų po tų 5s ir važiuotų toliau

2021-08-13 09:41 UTC, marmatu commented
Ačiū už patarimus. Atnaujinau testus ir pridėjau naujų.

2021-08-16 08:31 UTC, merged